### ISSUE TITLE
Strings outputting as hex.

### ISSUE THREAD

**Issue by Coriana** [fo76utils/fo76utils#1]
Have yet to get builds working locally to fix myself, but:

DURL
SNAM
FLTR
ALID
PEPI 
SCCM

are all strings that are currently set to hex. (at least when quests are concerned)

Should I get it building I will do a fork, and try do a pull request to fix, if you haven't already done som.

**Comment by Coriana** [comment]
Also. these are formids:

QTLM
QETL
QOTM

**Comment by fo76utils** [comment]
Added those and a few others as well, although SNAM does not always look like a file name.
