### ISSUE TITLE
Fallout 4 world render with/without story event changes (e.g. prydwen, uss constitution)

### ISSUE THREAD

**Issue by alexf13e** [fo76utils/fo76utils#11]
I have been using the render program to produce a map for my geoguesser game (thanks a lot for this by the way, the game would be barely 10% as enjoyable without a proper game map).

I would like to know if its possible to choose whether to include things like the prydwen and the uss constitution in the render, my reason being that for my game I have taken images at the start before those things appear/move, so it would be nice to reflect that in the map.

I'm not averse to modifying and rebuilding the program since its kind of specific to my use case, but I am also not really familiar with how these changes to the world are managed (e.g. is it just a case of different cells being loaded in, and certain ones can be specified to be rendered, or something more complicated like certain objects being loaded/swapped out when certain events have happened?)

Its not the biggest deal, but I thought I'd ask how feasible it would be.

Thanks

**Comment by fo76utils** [comment]
The render tool supports only static objects, so it does not account for objects spawned, moved or deleted by quest scripts. However, if you only need to disable certain models like the USS Constitution, that can be done with the -xm command line option, for example like this:

    -xm prydwenext -xm ussconstitution

These disable all meshes with a NIF path that contains 'prydwenext' or 'ussconstitution'.

**Comment by alexf13e** [comment]
That has worked perfectly for the uss constitution, the skyscraper one is gone but the bank remains.
It has removed the prydwen as well, but now I've noticed the debris and crashed vertibirds around the airport (and another vertibird I previously noticed near ticonderoga and bunker hill). Using `-xm vertibird` does remove the ones in question, but also others around the map I wish to keep such as the one on mass bay medical center.

I imagine I'll probably find other things I want to be more fussy about, is there a resource that lists model names which I could go through and try?

Slightly off topic as well, but there are some red tarp cover things such as to the east of CIT and on the highway north of corvega which don't get shown. Is there something I could try for these, or are they not counted as static objects?

In case it is worth noting, the full command I have been using is
`render "D:/Steam/steamapps/common/Fallout 4/Data/Fallout4.esm" fo4_map.dds 16384 16384 "D:/Steam/steamapps/common/Fallout 4/Data" -l 2 -view 0.0625 180 0 0 0 -1200 16384 -light 1 -35 100 -a -ssaa 1 -hqm meshes -env textures/shared/cubemaps/mipblur_defaultoutside1.dds -ltxtres 256 -deftxt 0x000BE9B6 -rq 15 -scol 1 -wtxt "" -xm prydwenext -xm ussconstitution -xm vertibird`

Thanks again

**Comment by fo76utils** [comment]
Model names can be found with the Creation Kit, but there is also an interactive version of render (wrldview), with a debug mode that can be activated by pressing '1'. In debug mode, clicking on any object prints its form ID, coordinates, and the model path.

> Slightly off topic as well, but there are some red tarp cover things such as to the east of CIT and on the highway north of corvega which don't get shown.

Can you show a screenshot of those, or the form ID if you can find one in game?

**Comment by alexf13e** [comment]
Can't access the game at the moment to check IDs, but here are screenshots of the ones I remembered off the top of my head, along with where they should be in the render.

![img_0091](https://github.com/user-attachments/assets/13c8c5ee-d9f9-49a6-aac3-782ee58af798)
![image](https://github.com/user-attachments/assets/a222202b-c06c-4a2a-84d8-4992f4b71a15)

![img_0151](https://github.com/user-attachments/assets/daf47e3b-98a7-4235-8d6a-c15b7f8825c3)
![image](https://github.com/user-attachments/assets/add8abbe-de5c-4f2c-bd4e-11ff8a379979)

**Comment by fo76utils** [comment]
I found the model, it is meshes/architecture/diamondcity/shackrv_ext/diamondredtarp02.nif. It is not rendered correctly because it is an animated (skinned) mesh, and skin data is not supported. Without using that, the tarp is at the ground level (this can be seen in NifSkope with skinning disabled), and most of it becomes invisible.

**Comment by alexf13e** [comment]
Using wrldview and comparing with looking in-game I managed to find all the meshes that get added to the airport, and did a render with and without them and just edited together the parts I wanted since its mostly debris and crates which are all over the map. I'm happy with this result, so my original question is answered.

For the tarps, I took what you said as meaning the orange part couldn't be rendered with the program but the supports could, so wanted to try rendering just the supports in debug mode so they would show brightly and I could go to those positions and manually edit something in. However, when fumbling a command together to try and render one of them with the form ID, it showed up properly (though not in the position I expected, but perhaps thats just from me not having any view option properly set). With this command I got the following output (cropped to just show the tarp, it was down and left a bit from the centre).
`render "D:/Steam/steamapps/common/Fallout 4/Data/Fallout4.esm" tarp.dds 2048 2048 "D:/Steam/steamapps/common/Fallout 4/Data" -l 2 -light 1 -35 100 -a -ssaa 1 -hqm meshes -env textures/shared/cubemaps/mipblur_defaultoutside1.dds -w 0x00164422 -r 0 0 0 0`
![image](https://github.com/user-attachments/assets/7e923b36-57d4-4cbb-8612-ea9998ca2a4d)

Is there a simple way of finding where all those tarps would be on the map, so that even if I can't get them to show as it has here I can just edit them in manually?

**Comment by fo76utils** [comment]
The tarps are rendered, but without skinning, they are moved to just below the ground level (as the NifSkope screenshot shows), and are usually occluded by the terrain.
![diamondredtarp02](https://github.com/user-attachments/assets/bae4cc65-5010-4b69-870d-20655c55efd2)

The easiest workaround is probably to create a modified version of the model where the tarps are manually moved to the correct place (translation by X=-20, Y=64, Z=224 looks about right), and to temporarily install it as a mod, saving the file as "D:/Steam/steamapps/common/Fallout 4/Data/meshes/architecture/diamondcity/shackrv_ext/diamondredtarp02.nif".

**Comment by alexf13e** [comment]
Thank you, that has done exactly what I wanted.
![image](https://github.com/user-attachments/assets/29e14b03-c72b-477c-b06f-74c5e8034fa4)
![image](https://github.com/user-attachments/assets/ffbc389f-0b0e-4626-9bf1-afea2e30f89e)

And just for fun, this is where the newly visible tarps are over the whole map (might need to zoom in a bit, and the colours are weird because I just xor'd it with the version missing them)
![image](https://github.com/user-attachments/assets/01363087-7648-4c48-816f-b187a01335cc)

There's probably other objects with a similar issue, but I haven't noticed them so am not bothered for now. If I find them in the future, I'll just refer back to this and see what I can do.

Thanks for all your help, I've never done any modding with the game besides just installing other people's, so didn't really know what to look for or what was feasible.
