### ISSUE TITLE
Is it possible to extract facegen textures using this?

### ISSUE THREAD

**Issue by ice051128** [fo76utils/fo76utils#6]
I'm trying to extract facegen textures from 76, does this work for the purpose?

**Comment by fo76utils** [comment]
If you are referring to the face textures under textures/actors/character/facecustomization, those can be extracted with a command like this:

`baunpack g:/SteamLibrary/steamapps/common/Fallout76/Data -- textures/actors/character/facecustomization`

However, if you are porting textures to Fallout 4, then they need conversion from 76's PBR system to work correctly in the older game.
