### ISSUE TITLE
Question applying render to Fallout 4

### ISSUE THREAD

**Issue by AHeroicLlama** [fo76utils/fo76utils#7]
Appreciate I'm working outside the intended use here but thought this worth asking...

Firstly - it works great for Fallout 4 out the box, great work!
However only when rendering the worldspace `Goodneighbor` (`00054BD5`), I recieve the error  "render: LandscapeData: landscape data not found for world in ESM file"

Full command:
`render.exe "C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\Fallout4.esm" out.dds 4096 4096 "C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data" -w 0x00054BD5`

Fallout 4 doesn't seem to have a .btd file which Fallout 76 has, however ommitting the `-btd` parameter works for rendering all other worldspaces - it's purely Goodneighbor which sees the error.

Do you have any advice in order to get the render of Goodneighbor working?

Thank you!

**Comment by fo76utils** [comment]
The Goodneighbor worldspace indeed does not seem to have any land data, it probably needs to use the landscape from the parent world (Commonwealth). I will try fixing this issue, and there are a number of other changes as well, so I will create a new binary release in the near future.

BTD files are new to Fallout 76, they are not used by the older games. However, you need to specify a default land texture, in the case of Fallout 4 with **-deftxt 0x000AB07E**.

For the DLCs, the ESM path needs to include both the base game and the DLC ESM, for example like **Fallout4/Data/Fallout4.esm,Fallout4/Data/DLCCoast.esm**. Loading more than one DLC at the same time does not work.

**Comment by AHeroicLlama** [comment]
Fantastic thank you very much - great points regarding the default texture and DLCs.
I look forward to the new release :)
