### ISSUE TITLE
NIF_INFO search finds similar files due to wildcard in prefix

### ISSUE THREAD

**Issue by kalechinees** [fo76utils/fo76utils#8]
Running into the issue with Starfield where NIF_Info is exporting "femalehead.nif" instead of "malehead.nif"

`./nif_info -obj "E:\SteamLibrary\steamapps\common\Starfield\data" "alehead.nif" > malehead.obj`

When we omit the first character of the query "alehead.nif", NIF_INFO still finds and exports "femalehead.nif" due to it appearing earlier in the alphabetical order. With this it's impossible to export malehead.nif.

edit:
Fixable by specifying the nif path, see below
./nif_info -obj -o malehead.obj "E:\SteamLibrary\steamapps\common\Starfield\data" meshes/actors/human/characterassets/male/malehead.nif

**Comment by fo76utils** [comment]
This is intended, the tool processes all files with a name that contains the pattern(s) you specified. If you only want to export data from malehead.nif, then use a more specific pattern like "/malehead.nif".
