### ISSUE TITLE
Documentation update?

### ISSUE THREAD

**Issue by reddraconi** [fo76utils/fo76utils#9]
It would be handy if there was a note about needing to pull the 'libfo76utils' submodule when cloning and building!

To successfully build on Fedora 39, I did the following:
1. Installed `python3-scons` by running `$sudo dnf install python3-scons`
2. Cloned this repo
3. cd'd into the cloned repo and ran `git submodule update --init --force`
4. Ran `scons -j 16`

**Comment by fo76utils** [comment]
I added a note about submodules to README.md in the "Building from source code" section.
